before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: 0Z1QGNEeTmRgcmcvPU9o9KhNu8ZC1EAMJi/2LrqDTmaPrJXGg5qJqznRXQhE/Xzt2Dq3mrzxPSIuqoSCqEd89a/BLXCpCOYjoHcn8RBEgb5NkTyElyu14XBxmqxl4e6w+pTntN2vt7NmCWzr7x7qouWQ0VC1+5nRZOaCsJKj8aWptFwS/soOJrzMW1WaUpC5l/c2B+uvfVoFEMpz5x+WZJfNk6ggG0d8KDZvohaCxR623vRwGKbEOG4zD9dXTDwEd1Fep+8x6TMPo4OSvxpJD8HWI+rN6vEBPQ68SfHe/UqnIJh8grWR/2Uu9bKPJISYrzcTycQ/GlugqWUblXvs+2sGcbF606QLl/iq/FTHBz+vn92SqLG2dOYX4bMT/ul0Bo61+Mw8O80cO+16gxdHCwzm0i1zsPOVIpI2lbHtbJPdFWe+UWyDay9vq5CCjS0/HKKZTkSgTWVI9t7giehMj1lMqltMaTibsgi4r/KHBC4fhpR+T6D1KXTiQpyulKoCHOdGdw1vl4GXdsWoBR6V+NI6n6XmzzRodity7gpPm2q1BFzH1aFtZgektUJ9ELOv9nefHO3i6v2f8GfLZibehXBoV9Of83r1QLfEd7KrOSyYyK+M8uAHbEdIYjPMSotAYAc/0blm5K3YqaAVNJFU0adNnIjNwLwTOeC88sFzYwg= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
